# Generated by Django 5.0.1 on 2024-01-17 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0002_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='paid_course',
            field=models.CharField(choices=[('course', 'Курс'), ('lesson', 'Урок')], default='course', verbose_name='Что оплачено'),
        ),
    ]
