# Generated by Django 5.0.1 on 2024-01-17 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0003_alter_payments_paid_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lesson.lesson', verbose_name='Уроки'),
        ),
    ]
