# Generated by Django 5.0.1 on 2024-01-29 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0008_payments_amount_payments_is_paid_payments_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='amount',
            field=models.ImageField(default=100, upload_to='', verbose_name='сумма оплаты'),
        ),
    ]
