# Generated by Django 5.0.1 on 2024-01-29 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0010_payments_course_payments_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='amount',
            field=models.IntegerField(default=100, verbose_name='сумма оплаты'),
        ),
    ]
