# Generated by Django 5.0.1 on 2024-01-31 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0012_course_date_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='date_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
