# Generated by Django 4.2.9 on 2024-01-31 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0013_alter_course_date_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='date_preview',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
